name: CI for Vite React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '17'

    - name: Install dependencies
      run: |
        npm install

    - name: Build the application
      run: |
        npm run build

    - name: Build Docker image
      run: |
        docker build -t 24-25j-030-wq-web .

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        docker tag 24-25j-030-wq-web ${{ secrets.DOCKER_USERNAME }}/24-25j-030-wq-server:tagname
        docker push ${{ secrets.DOCKER_USERNAME }}/24-25j-030-wq-server:tagname
