name: CI for Vite React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        node-version: '20'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      working-directory: ./wq-web
      run: npm install

    - name: Build the application
      working-directory: ./wq-web
      run: npm run build

    - name: Build Docker image
      run: |
        docker build -t wq-web ./wq-web  # Build the Docker image and tag it as wq-web

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        node-version: '20'

    - name: Push Docker image to Docker Hub
      run: |
        docker tag wq-web kaveeshait21258794/24-25j-030-wq-server:wq-web  # Tag the image with wq-web
        docker push kaveeshait21258794/24-25j-030-wq-server:wq-web  # Push to Docker Hub with wq-web tag
