name: CI/CD for Vite React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      working-directory: ./wq-web
      run: npm install

    - name: Build the application
      working-directory: ./wq-web
      run: npm run build

    - name: Build Docker image
      run: |
        docker build -t wq-web ./wq-web

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image to Docker Hub
      run: |
        docker tag wq-web kaveeshait21258794/24-25j-030-wq-server:wq-web
        docker push kaveeshait21258794/24-25j-030-wq-server:wq-web

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH key
      run: |
        echo "${{ secrets.EC2_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Deploy to Amazon Linux EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.EC2_HOST }} << EOF
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          sudo docker pull kaveeshait21258794/24-25j-030-wq-server:wq-web
          sudo docker stop wq-web || true
          sudo docker rm wq-web || true
          sudo docker run -d -p 80:80 --name wq-web kaveeshait21258794/24-25j-030-wq-server:wq-web
        EOF
